In [ ]:
import h5py
import pyUSID

# 아래 출력은 html과 같지만 구조가 달라 삭제함
hf = h5py.File('pyusid.h5','r+')
h5_main = pyUSID.hdf_utils.find_dataset(hf, 'Raw_Data')[0]
print(h5_main)


<HDF5 dataset "Raw_Data": shape (100, 54560), type "<c8">
located at: 
	/Measurement_000/Channel_000/Raw_Data 
Data contains: 
	quantity (a.u.) 
Data dimensions and original shape: 
Position Dimensions: 
	X - size: 10 
	Y - size: 10 
Spectroscopic Dimensions: 
	Frequency - size: 124 
	Field - size: 2 
	write_bias - size: 20 
	read_bias - size: 11
Data Type:
	complex64


In [93]:
import numpy as np
# get_frequency_vector
h5_spec_vals = h5_main.h5_spec_vals
freq_dim = np.argwhere('Frequency' == np.array(h5_main.spec_dim_labels)).squeeze()

print(h5_spec_vals,freq_dim)

<HDF5 dataset "Spectroscopic_Values": shape (4, 54560), type "<f4"> 0


In [94]:
h5_main.h5_spec_inds[0]

array([  0,   0,   0, ..., 123, 123, 123], dtype=uint32)

In [41]:
freq_dim_ind = h5_main.spec_dim_labels.index('Frequency')
step_start_inds = np.where(h5_main.h5_spec_inds[freq_dim_ind] == 0)[0]

freq_dim_ind

0

In [75]:
len(h5_main.h5_spec_inds[0])

54560

In [43]:
len(step_start_inds)

440

In [44]:
step_start_inds

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [59]:
freq_vec = h5_spec_vals[freq_dim,step_start_inds[0]:step_start_inds[1]]
freq_vec

array([0.], dtype=float32)

In [3]:
import h5py
import pyUSID
hf = h5py.File('pyusid.h5','r+')
h5_main = pyUSID.hdf_utils.find_dataset(hf, 'Raw_Data')[0]
print(h5_main)

<HDF5 dataset "Raw_Data": shape (100, 54560), type "<c8">
located at: 
	/Measurement_000/Channel_000/Raw_Data 
Data contains: 
	quantity (a.u.) 
Data dimensions and original shape: 
Position Dimensions: 
	Y - size: 10 
	X - size: 10 
Spectroscopic Dimensions: 
	read_bias - size: 11 
	write_bias - size: 20 
	Field - size: 2 
	Frequency - size: 124
Data Type:
	complex64


In [5]:
import numpy as np
h5_spec_vals = h5_main.h5_spec_vals
freq_dim = np.argwhere('Frequency' == np.array(h5_main.spec_dim_labels)).squeeze()

print(h5_spec_vals,freq_dim)

<HDF5 dataset "Spectroscopic_Values": shape (4, 54560), type "<f4"> 3


In [78]:
np.array(h5_main.spec_dim_labels)

array(['read_bias', 'write_bias', 'Field', 'Frequency'], dtype='<U10')

In [79]:
freq_dim_ind = h5_main.spec_dim_labels.index('Frequency')
step_start_inds = np.where(h5_main.h5_spec_inds[freq_dim_ind] == 0)[0]

In [80]:
len(step_start_inds)

440

In [81]:
h5_main.h5_spec_inds[3]

array([  0,   1,   2, ..., 121, 122, 123], dtype=uint32)

In [82]:
len(h5_main.h5_spec_inds[3])

54560

In [84]:
h5_main.h5_spec_inds[3][0:125]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123,   0], dtype=uint32)

In [64]:
step_start_inds

array([    0,   124,   248,   372,   496,   620,   744,   868,   992,
        1116,  1240,  1364,  1488,  1612,  1736,  1860,  1984,  2108,
        2232,  2356,  2480,  2604,  2728,  2852,  2976,  3100,  3224,
        3348,  3472,  3596,  3720,  3844,  3968,  4092,  4216,  4340,
        4464,  4588,  4712,  4836,  4960,  5084,  5208,  5332,  5456,
        5580,  5704,  5828,  5952,  6076,  6200,  6324,  6448,  6572,
        6696,  6820,  6944,  7068,  7192,  7316,  7440,  7564,  7688,
        7812,  7936,  8060,  8184,  8308,  8432,  8556,  8680,  8804,
        8928,  9052,  9176,  9300,  9424,  9548,  9672,  9796,  9920,
       10044, 10168, 10292, 10416, 10540, 10664, 10788, 10912, 11036,
       11160, 11284, 11408, 11532, 11656, 11780, 11904, 12028, 12152,
       12276, 12400, 12524, 12648, 12772, 12896, 13020, 13144, 13268,
       13392, 13516, 13640, 13764, 13888, 14012, 14136, 14260, 14384,
       14508, 14632, 14756, 14880, 15004, 15128, 15252, 15376, 15500,
       15624, 15748,

In [15]:
from BGlib import be as belib

sho_fitter = belib.analysis.BESHOfitter(h5_main, cores=None, verbose=False, h5_target_group=hf)
sho_fitter.set_up_guess(guess_func=belib.analysis.be_sho_fitter.SHOGuessFunc.complex_gaussian,
                        num_points=5)
h5_sho_guess = sho_fitter.do_guess(override=True)
sho_fitter.set_up_fit()
h5_sho_fit = sho_fitter.do_fit(override=True)
h5_sho_grp = h5_sho_fit.parent

Consider calling test() to check results before calling compute() which computes on the entire dataset and writes results to the HDF5 file
	This class (likely) supports interruption and resuming of computations!
	If you are operating in a python console, press Ctrl+C or Cmd+C to abort
	If you are in a Jupyter notebook, click on "Kernel">>"Interrupt"
	If you are operating on a cluster and your job gets killed, re-run the job to resume

Rank 0 finished parallel computation
Rank 0 - 100% complete. Time remaining: 0.0 msec
Finished processing the entire dataset!

Note: SHO_Fit has already been performed with the same parameters before. These results will be returned by compute() by default. Set override to True to force fresh computation

[<HDF5 group "/Raw_Data-SHO_Fit_000" (4 members)>]
Resuming computation. 0% completed already
	This class (likely) supports interruption and resuming of computations!
	If you are operating in a python console, press Ctrl+C or Cmd+C to abort
	If you are in

c:\test_pycroscopy\bglib\BGlib\be\analysis\fitter.py:140: UserWarning: status dataset not created yet
  warn('status dataset not created yet')


Rank 0 - 100% complete. Time remaining: 0.0 msec
Finished processing the entire dataset!


In [16]:
h5_sho_fit

<HDF5 dataset "Fit": shape (100, 440), type "|V40">
located at: 
	/Raw_Data-SHO_Fit_000/Fit 
Data contains: 
	SHO (compound) 
Data dimensions and original shape: 
Position Dimensions: 
	Y - size: 10 
	X - size: 10 
Spectroscopic Dimensions: 
	read_bias - size: 11 
	write_bias - size: 20 
	Field - size: 2
Data Fields:
	Amplitude [V], Frequency [Hz], Quality Factor, Phase [rad], R2 Criterion

In [17]:
import pyUSID as usid
import h5py

usid.hdf_utils.print_tree(hf)

/
├ Measurement_000
  ---------------
  ├ Channel_000
    -----------
    ├ Position_Indices
    ├ Position_Values
    ├ Raw_Data
    ├ Raw_Data-SHO_Fit_000
      --------------------
      ├ Fit
      ├ Guess
      ├ Spectroscopic_Indices
      ├ Spectroscopic_Values
      ├ completed_fit_positions
      ├ completed_guess_positions
    ├ Spectroscopic_Indices
    ├ Spectroscopic_Values
├ Raw_Data-SHO_Fit_000
  --------------------
  ├ Fit
  ├ Guess
  ├ Spectroscopic_Indices
  ├ Spectroscopic_Values
  ├ completed_fit_positions
  ├ completed_guess_positions


In [10]:
# sho_fit 이 Channel_000안에 있는 것을 확인하여 이동
hf.copy('/Raw_Data-SHO_Fit_000','/Measurement_000/Channel_000/Raw_Data-SHO_Fit_000')
usid.hdf_utils.print_tree(hf)


/
├ Measurement_000
  ---------------
  ├ Channel_000
    -----------
    ├ Position_Indices
    ├ Position_Values
    ├ Raw_Data
    ├ Raw_Data-SHO_Fit_000
      --------------------
      ├ Fit
      ├ Guess
      ├ Spectroscopic_Indices
      ├ Spectroscopic_Values
      ├ completed_fit_positions
      ├ completed_guess_positions
    ├ Spectroscopic_Indices
    ├ Spectroscopic_Values
├ Raw_Data-SHO_Fit_000
  --------------------
  ├ Fit
  ├ Guess
  ├ Spectroscopic_Indices
  ├ Spectroscopic_Values
  ├ completed_fit_positions
  ├ completed_guess_positions


In [18]:
del hf['/Raw_Data-SHO_Fit_000']
usid.hdf_utils.print_tree(hf)


/
├ Measurement_000
  ---------------
  ├ Channel_000
    -----------
    ├ Position_Indices
    ├ Position_Values
    ├ Raw_Data
    ├ Raw_Data-SHO_Fit_000
      --------------------
      ├ Fit
      ├ Guess
      ├ Spectroscopic_Indices
      ├ Spectroscopic_Values
      ├ completed_fit_positions
      ├ completed_guess_positions
    ├ Spectroscopic_Indices
    ├ Spectroscopic_Values


In [19]:
usid.hdf_utils.print_tree(hf)

/
├ Measurement_000
  ---------------
  ├ Channel_000
    -----------
    ├ Position_Indices
    ├ Position_Values
    ├ Raw_Data
    ├ Raw_Data-SHO_Fit_000
      --------------------
      ├ Fit
      ├ Guess
      ├ Spectroscopic_Indices
      ├ Spectroscopic_Values
      ├ completed_fit_positions
      ├ completed_guess_positions
    ├ Spectroscopic_Indices
    ├ Spectroscopic_Values


In [ ]:
Nd_mat = h5_sho_fit.get_n_dim_form()
print('Nd_mat shape = ', Nd_mat.shape)

phase_offset = Nd_mat[0, 0, 1, 0, 0]['Phase [rad]']

print('Phase offset [rad] = ', phase_offset)

Nd_mat[:,:,:,:,:]['Phase [rad]'] = Nd_mat[:,:,:,:,:]['Phase [rad]'] - phase_offset


Nd_mat shape =  (10, 10, 11, 20, 2)
Phase offset [rad] =  0.1405820995569229
